nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

packageExtensions:
  cosmiconfig-typescript-loader@*:
    peerDependenciesMeta:
      "@types/node":
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.5.1.cjs
